# Generated by Django 3.2 on 2024-02-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240206_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
